name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Prisma migration and client generation steps
    - name: Apply migration
      run: cargo prisma migrate deploy
    - name: Generate Prisma Client
      run: cargo prisma generate

    # Build Rust project
    - name: Build
      run: cargo build --release

    # Run tests if needed
    - name: Run tests
      run: cargo test

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ghcr.io/yourusername/myapp:latest .

    # Log in to Docker
    - name: Log in to Docker
      run: echo "$DOCKER_PASSWORD" | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin

    # Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: docker push ghcr.io/yourusername/myapp:latest
